### ISSUE TITLE
Rewrite, or support for modern PHP and OS'

### ISSUE THREAD

**Issue by siniStar7** [UndernetIRC/cservice-web#1]
I was curious if there was an effort to make the cservice-website either operable under modern OS' and PHP versions?

I would be interested in helping with a web interface re-write or possible updates..  

Our network utilizes GNUworld, but we do not have any boxes _(or hosts)_ that will allow us to install the _older_ OS versions or PHP versions..

**Comment by Ratler** [comment]
Should now work with php 7.
