### ISSUE TITLE
Website login on * account using local IP addresses

### ISSUE THREAD

**Issue by ZioNeL** [UndernetIRC/cservice-web#11]
In order to permit login on CService Web from local IP address like 192.168.xx.xx or 10.0.0.xx the following changes must be made:

1. in cmaster.inc change if (cl_ip()=="0.0.0.0") { die("For some reason we cannot determine your IP, you cannot access this service."); } to #if (cl_ip()=="0.0.0.0") { die("For some reason we cannot determine your IP, you cannot access this service."); }

2. on login.php file delete the following lines:

             if (cl_ip() == "0.0.0.0") { // safety valve. (useless?)
                     header("Pragma: no-cache");
                     echo "<META HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\n";
                     echo "<html>\n";
                     echo "<head><title>Error</title>";
                     std_theme_styles();
                     echo "</head>";
                     std_theme_body();
                     echo "<font size=+0>\n";
                     echo "You can't login using your current IP number.<br><br>";
                     echo "<a href=\"index.php\" target=\"_top\">click here</a>.<br>\n";
                     echo "</font></body></html>\n\n";
                     die;
             }
3. create ipr.sql file to insert the ip address in ip_restrict table:
nano ipr.sql
insert into ip_restrict (id, user_id, added_by, added, type, expiry, value) values (1, 1, 1, now()::abstime::int4, 1, 0, '0.0.0.0'); 
Save and close.
.
4. /usr/local/pgsql/bin/psql cservice < ipr.sql

Now login using * accounts from local IP address is possible.

**Comment by Ratler** [comment]
You can allow the RFC1918 address space by changing this configuration in config.inc (no need to comment out any code):
`define("DISALLOW_RESERVED_BLOCKS",1);`
to
`define("DISALLOW_RESERVED_BLOCKS",0); `

**Comment by ZioNeL** [comment]
Hey Ratler, Thank you very much for the info provided. I`ve tested it and it works.
I have one more thing to ask you. It is possible to solve define("IPR_REQUIRED" ? Even if is set to 0, * accounts require to have ip`s set on ip_restrict table in order to login on webpage.

**Comment by Ratler** [comment]
Not sure I understand your question. Either you require IPR, or you don't. But if you disable IPR_REQUIRED and add an ip for a specific user, then it will be required for that user, but not for anyone else. In other words with IPR_REQUIRED set 0, it becomes optional rather then required.

**Comment by ZioNeL** [comment]
I will try to explain as simple as i can. 
Even with IPR_REQUIRED set to 0 , * accounts are unable to login on webpage if they don`t have the ip address insert in the ip_restrict table. If IPR_REQUIRED worked , when value is set to 0, * accounts should be able to login on webpage without any IP entry.
