### ISSUE TITLE
website error

### ISSUE THREAD

**Issue by tenye2003** [UndernetIRC/cservice-web#17]
Hello. There are some error on cservice-web. 
1) New username register stuck at step 3/6 (where you need to complete the email adress but there is no box). 
2) Missing managers not working - http://127.0.0.1/gnuworld/admin/bmnew/bmnew.php This page isn’t working127.0.0.1 is currently unable to handle this request.
HTTP ERROR 500
3)Same to view manager changes http://127.0.0.1/gnuworld/xat/mgrchg/mgr_change.php - same error as above.

**Comment by ZioNeL** [comment]
Hello,
Try to use the webpage with a real ip address and not 127.0.0.1 . I got the code and to me is working.

**Comment by tenye2003** [comment]
hi ,
I tried with real ip , same error. I enabled display errors on the file and the result is
Fatal error: Uncaught Error: Undefined constant "on" in /home/gnuworld/cservice-web/docs/gnuworld/admin/bmnew/bmnew.php:26 Stack trace: #0 {main} thrown in /home/gnuworld/cservice-web/docs/gnuworld/admin/bmnew/bmnew.php on line 26

**Comment by tenye2003** [comment]
Hi,
I tried that ,i got the same problem. I enable displayer_error on php and when i try access missing managers i got
Fatal error: Uncaught Error: Undefined constant "on" in /home/gnuworld/cservice-web/docs/gnuworld/admin/bmnew/bmnew.php:25 Stack trace: #0 {main} thrown in /home/gnuworld/cservice-web/docs/gnuworld/admin/bmnew/bmnew.php on line 25

**Comment by ZioNeL** [comment]
the webpage is woring fine on my server.
For what i can tell is something  from your end.
check what you have on line 25 and 26 on /home/gnuworld/cservice-web/docs/gnuworld/admin/bmnew/bmnew.php .

**Comment by tenye2003** [comment]
I dont know what is the problem , i didnt modified anything . gnuworld works perfectly. But the website has this errors. cant even create a new username since it stucks at step 3/6. Might be something related to php ? (i use PHP 8.1.2)

**Comment by ZioNeL** [comment]
at the moment cservice web, is not working with PHP 8. Try running it using php 7.4.x

**Comment by tenye2003** [comment]
Thanks. Downgraded to php 7.4 everything works fine now.
