### ISSUE TITLE
cmaster.inc generates "unexpected end of file" error

### ISSUE THREAD

**Issue by StoneC0ld** [UndernetIRC/cservice-web#3]
I tried hunting the problem down in Notepad++ with its fancy text/syntax colors and matching of block sections, but I can't find it for the life of me....  Several online php syntax checkers revealed nothing.

 Setting up the php7 branch of the cservice website brand new (after modifying config.inc), all I get in the main frame is an error:  "Parse error: syntax error, unexpected end of file in /var/www/cservice-web/php_includes/cmaster.inc on line 3327"

**Comment by Ratler** [comment]
Please check if it is still an issue. Otherwise feel free to re-open this issue.
